"""adds pitch

Revision ID: 36d7e307135b
Revises: 73dd1557e12d
Create Date: 2019-06-29 21:01:22.526854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d7e307135b'
down_revision = '73dd1557e12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('pitch_body', sa.String(), nullable=True))
    op.add_column('pitch', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('pitch', sa.Column('posted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'posted_by')
    op.drop_column('pitch', 'posted_at')
    op.drop_column('pitch', 'pitch_body')
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###
