"""bio

Revision ID: 498e531e1979
Revises: cda5ac57230a
Create Date: 2019-06-29 17:56:41.005469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498e531e1979'
down_revision = 'cda5ac57230a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
